[project]
name = "video-analysis-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.118.0",
    "httpx>=0.28.1",
    "motor>=3.7.1",
    "opencv-python>=4.12.0.88",
    "pillow>=11.3.0",
    "pydantic-settings>=2.11.0",
    "pymysql>=1.1.2",
    "python-multipart>=0.0.20",
    "sqlmodel>=0.0.25",
    "ultralytics>=8.3.206",
    "uvicorn[standard]>=0.37.0",
]
